server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:Mappers/*.xml
logging:
#  level: debug
  path: D:\gitHub\springboot\log